language: node_js
node_js:
    - 6
cache:
    directories:
        - node_modules

before_install:
    - npm install -g firebase-tools
    - cd functions
    - npm install
    - cd ..

script:
    - npm test
    - echo "deploying"

after_success:
    - npm run build
    - firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN

branches:
    only:
        - master
